"""Storage contracts used by inventory rules and approval orchestration."""

from contextlib import AbstractContextManager
from dataclasses import dataclass
from typing import Any, Protocol

from .models import Part


class RepositoryConflict(Exception):
    """A write violates a storage uniqueness or integrity constraint."""


@dataclass(frozen=True)
class StoredApproval:
    request_id: str
    thread_id: str
    tool_name: str
    arguments: dict[str, Any]
    snapshot: dict[str, Any]
    decision: bool | None = None
    result: dict[str, Any] | None = None


class InventoryRepository(Protocol):
    def search(self, filters: dict[str, Any]) -> list[Part]: ...
    def get(self, part_id: int) -> Part | None: ...
    def find_duplicate(self, fields: dict[str, Any]) -> Part | None: ...
    def insert(self, fields: dict[str, Any]) -> int: ...
    def increment_stock(self, part_id: int, quantity: int) -> None: ...
    def replace_parts(self, updates: list[tuple[int, dict[str, Any]]]) -> None: ...
    def delete(self, part_id: int) -> None: ...
    def list_pending_reviews(self) -> dict[int, dict[str, Any]]: ...
    def save_pending_review(self, part_id: int, fields: dict[str, Any], provenance: list[dict[str, Any]]) -> None: ...
    def stage_enrichment_if_unchanged(self, original: Part, fields: dict[str, Any], provenance: list[dict[str, Any]]) -> bool: ...
    def clear_pending_review(self, part_id: int, fields: list[str] | None = None) -> None: ...
    def update_with_provenance(self, part_id: int, fields: dict[str, Any], provenance: list[dict[str, Any]]) -> None: ...
    def list_provenance(self, part_id: int) -> list[dict[str, Any]]: ...


class ApprovalRepository(Protocol):
    def insert(self, approval: StoredApproval) -> None: ...
    def get(self, thread_id: str, request_id: str) -> StoredApproval | None: ...
    def set_decision(self, request_id: str, approved: bool) -> None: ...
    def save_result(self, request_id: str, result: dict[str, Any]) -> None: ...


class Savepoint(Protocol):
    def rollback(self) -> None: ...


class PartsBinRepository(Protocol):
    """One transaction boundary for inventory, review evidence, and approval outcomes.

    Transactions serialize competing writes and bind both repositories to the same
    unit of work. Exceptions roll back the unit; savepoints allow a rejected domain
    operation to roll back while its failure outcome is retained.
    """

    storage_id: str
    inventory: InventoryRepository
    approvals: ApprovalRepository

    def transaction(self) -> AbstractContextManager["PartsBinRepository"]: ...
    def savepoint(self) -> AbstractContextManager[Savepoint]: ...
